# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ZHTestSDK' do
  use_frameworks!
  
  pod 'SDWebImage'

end

target 'ZHTestSDKDemo' do
  use_frameworks!

  pod 'SDWebImage'
  
end
